version: '3.0.6'

services:
  database:
    image: postgres
    restart: always
    container_name: database_1
    ports:
      - 5433:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: market
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  application:
    image: application-image
    container_name: application_1
    ports:
      - 80:80
    depends_on:
      - database
    environment:
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=qwerty"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/market"

volumes:
  postgres_volume:
    external: true